import { Router } from "express";
import { schemaValidator } from "../middlewares/schemaValidator.middleware.js";
import {
  authRequired,
  emailTokenRequired,
  passwordTokenRequired,
} from "../middlewares/tokenValidator.middleware.js";
import { signupSchema, signinSchema } from "../schemas/auth.schema.js";
import {
  signIn,
  signUp,
  signOut,
  myProfile,
  updateProfile,
  forgotPassword,
  newPassword,
  otherUserProfile,
  userConfirmed,
} from "../controllers/auth.controller.js";
import { fileUploadMiddleware } from "../middlewares/fileUpload.middleware.js";

const router = Router();

/**
 * @swagger
 * components:
 *    schemas:
 *      User:
 *        type: object
 *        required:
 *            - username
 *            - email
 *            - password
 *        properties:
 *          id:
 *            type: ObjectId
 *            description: auto-generated id by mongodb of the post
 *          username:
 *            type: string
 *            description: username of the user
 *          email:
 *            type: string
 *            description: email's user
 *          password:
 *            type: string
 *            description: password's user encrypted by bcryptjs
 *          description:
 *            type: string
 *            description: description's user.
 *          superuser:
 *            type: Boolean
 *            default: false
 *            description: If the user is a superuser or not
 *          image:
 *            public_id: generated by cloudinary
 *            secure_url: generated by cloudinary
 *            description: user's profile image.
 *            required: false
 *          createdAt:
 *            type: Date
 *            description: Post's creation date
 *          updatedAt:
 *            type: Date
 *            description: Post's last update date
 *        example:
 *            _id: 4889873042ds093412
 *            username: potato123
 *            email: potato123@gmail.com
 *            password: $2a$10$wRLYZidb7855567gkP4nxuVg0Jdl7RVTSU.4ADH0XB.uOeml3T3rS
 *            description: hello everyone, im potato123 and i love videogames.
 *            image:
 *                public_id: 12345qwerty69
 *                secure_url: https://res.cloudinary.com/dqwqmhxqh/image/upload/v1647391329/potato123_zcxzqo.jpg
 *            createdAt: 2022-01-01T00:00:00.000Z
 *            updatedAt: 2022-01-01T00:00:00.000Z
 *        headers:
 *            token:
 *              description: token generated to use the protected routes.
 *              schema:
 *                type:  string
 *                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODk3MzgwYjA0NzUwMDAwMDAwIiwiaWF0IjoxN
 */

/**
 * @swagger
 * /api/signup:
 *    post:
 *      summary: register a new user
 *      description: register a new user and return his information with an access token in set-cookie in the header called token.
 *      tags: [Users]
 *      requestBody:
 *        required: true
 *        content:
 *          application/json:
 *            schema:
 *             type: object
 *             properties:
 *                email:
 *                  type: string
 *                username:
 *                  type: string
 *                password:
 *                  type: string
 *      responses:
 *        200:
 *          description: new user registered
 *          content:
 *            application/json:
 *              schemas:
 *                type: array
 *                items:
 *                  $ref: '#/components/schemas/User'
 *        400:
 *          description: email or password already exists.
 *        500:
 *          description: Some server error
 */

/**
 * @swagger
 * tags:
 *  name: Users
 *  description: The suscription managing API
 */

router.post(
  "/signup",
  fileUploadMiddleware,
  schemaValidator(signupSchema),
  signUp
);

router.post("/user-confirmed/:id/:token", emailTokenRequired, userConfirmed);

/**
 * @swagger
 * /api/signin:
 *  post:
 *    summary: user login
 *    description: login an user and return his information with an access token in set-cookie in the header called token.
 *    tags: [Users]
 *    requestBody:
 *      required: true
 *      content:
 *        application/json:
 *          schema:
 *            type: object
 *            properties:
 *              email:
 *                type: string
 *              password:
 *                type: string
 *    responses:
 *      200:
 *        description: user logged in
 *        content:
 *          application/json:
 *            example:
 *                id: 3284578548gd9493vn
 *                username: potato123
 *                email: potato123@gmail.com
 *                superuser: false
 *            headers:
 *               set-cookie:
 *                  description: cookie to save the access token to others endpoints
 *                  type: string
 *                  example: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGU3NTlmNTQ3YzA3MTU0YdfSDFGHdfe54gdcGVydXNlciI6ZmFsc2UsImlhdCI6MTY5MjMwMDcwMywiZXhwIjoxNjkyMzg3MTAzfQ.rmNibFYMo8cRdVoW2QLcYw_lB2jHirstbrNrnWpSdEM; Path=/
 *      400:
 *          description: invalid credentials.
 *      500:
 *        description: Some server error
 */

router.post("/signin", schemaValidator(signinSchema), signIn);

/**
 * @swagger
 * /api/signout:
 *  post:
 *    summary: user logout
 *    description: logout an user and it deletes his token in the header called token.
 *    tags: [Users]
 *    security:
 *       - cookieAuth: []
 *    responses:
 *      200:
 *        description: user logout and token deleted
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/User'

 */

router.post("/signout", authRequired, signOut);

/**
 * @swagger
 * /api/profile/{id}:
 *    get:
 *      summary: Get a user profile by its id
 *      tags: [Users]
 *      security:
 *        - bearerAuth: []
 *      responses:
 *        200:
 *          description: user information
 *          contens:
 *            application/json:
 *              example:
 *                username: "potato123"
 *                email:  "potato123@gmail.com"
 *                createdAt: "YYYY-MM-DDTHH:MM:SS.000Z"
 *                description: i am a potato
 *                password: "hashed_password_here"
 *                image: {
 *                       secure_url: "url provided by cloudinary"
 *                      }
 *        401:
 *          description: token invalid.
 *        404:
 *          description: User not found.
 */

router.get("/profile", authRequired, myProfile);

router.get("/profile/:id", otherUserProfile);

/**
 * @swagger
 * /api/profile/{id}:
 *  put:
 *    summary: Update profile
 *    tags: [Users]
 *    security:
 *       - cookieAuth: []
 *    parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: ObjectId
 *         required: true
 *         description: The user id
 *    requestBody:
 *      required: true
 *      content:
 *        application/json:
 *          schema:
 *            $ref: '#/components/schemas/Post'
 *    responses:
 *      200:
 *        description: the profile was updated
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/Post'
 *      401:
 *        description: token invalid.
 *      403:
 *        description: unauthorized, only owners's profile are allowed to update their profiles.
 *      404:
 *        description: user not found
 *      500:
 *        description: some error server.
 *
 */

router.put("/profile", authRequired, fileUploadMiddleware, updateProfile);

/**
 * @swagger
 * /api/forgot-password:
 *  post:
 *    summary: Request password reset
 *    description: An email will be sent to the user with a link to reset the password.
 *    tags: [Users]
 *    parameters:
 *      - in: body
 *        name: email
 *        schema:
 *          type: string
 *        required: true
 *        description: user's email address.
 *
 */

router.post("/forgot-password", forgotPassword);

router.post("/reset-password/:id/:token", passwordTokenRequired, newPassword);

export default router;
